//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleHouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int Id { get; set; }
        public int HouseId { get; set; }
        public int Number { get; set; }
        public decimal Area { get; set; }
        public int RoomAmount { get; set; }
        public int EnterNumber { get; set; }
        public int FloorNumber { get; set; }
        public int SaleStatusId { get; set; }
        public decimal AdditionalPrice { get; set; }
        public decimal BuildingPrice { get; set; }
    
        public virtual House House { get; set; }
        public virtual SaleStatus SaleStatus { get; set; }
    }
}
