//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleHouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseComplex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseComplex()
        {
            this.House = new HashSet<House>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public Nullable<decimal> AdditionalPrice { get; set; }
        public decimal BuildingPrice { get; set; }
        public int BuildStatusId { get; set; }
    
        public virtual BuildStatus BuildStatus { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> House { get; set; }
    }
}
