//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleHouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Apartment = new HashSet<Apartment>();
        }
    
        public int Id { get; set; }
        public int StreetId { get; set; }
        public string Number { get; set; }
        public decimal BuildingPrice { get; set; }
        public decimal AdditionalPrice { get; set; }
        public int HouseComplexId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartment { get; set; }
        public virtual HouseComplex HouseComplex { get; set; }
        public virtual Street Street { get; set; }
    }
}
